"""added lab_id and patient_email

Revision ID: 75446e92e076
Revises: 
Create Date: 2026-03-17 01:09:22.829733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75446e92e076'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('patient_email', sa.String(length=120), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'lab', ['lab_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('patient_email')
        batch_op.drop_column('lab_id')

    # ### end Alembic commands ###
